### ISSUE TITLE
Add library in android studio not found

### ISSUE THREAD

**Issue by TuanKhanhRA** [Kucoin/kucoin-java-sdk#23]
My code: build.gradle
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    implementation 'junit:junit:4.13'
    implementation 'androidx.test.ext:junit:1.1.2'
    implementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.kucoin:kucoin-java-sdk:2.0.0'
} 

Error: Failed to resolve: com.kucoin:kucoin-java-sdk:2.0.0
Show in Project Structure dialog
Affected Modules: app

I really don't know what the syntax in gradle file looks like!

Thanks,

**Comment by 1bazinga25** [comment]
Hava you fixed this issue?

**Comment by hamidghasemy** [comment]
I have the same problem

**Comment by ISAAC-XXYYZZ** [comment]
Due to many changes in the SDK, Please try updating to the latest version of the SDK（1.0.14） and modify your code to try again. If you encounter any issues, feel free to provide feedback.
