### ISSUE TITLE
Can't compile in IntelliJ

### ISSUE THREAD

**Issue by tommyzat** [Kucoin/kucoin-java-sdk#34]
I'm getting about 60 "java: cannot find symbol" errors, only when building. I tried everything. The errors don't appear in the live text editor, only when compiling.

**Comment by sfergu** [comment]
I was able to get this to build in intelliJ by making the following lombok change to the pom, and then be sure to build with a maven task 


      <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.2</version>
            <scope>compile</scope>
        </dependency>



maven clean install with the skip tests checked installed it to my local maven repo

**Comment by leehus** [comment]
@sfergu 
Life Saver!!
