### ISSUE TITLE
Clean Install on Eclipse Error

### ISSUE THREAD

**Issue by Mafiat0m** [Kucoin/kucoin-java-sdk#39]
When trying to make a clean install in Eclipse im am Getting the Error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project kucoin-java-sdk: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]

**Comment by Mafiat0m** [comment]
With that
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.LombokProcessor to field com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs
WARNING: Please consider reporting this to the maintainers of lombok.javac.apt.LombokProcessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by pythoneer** [comment]
Apparently this library does not work with e.g. Java >= 11 and i had to install an ancient Java 8 (openjdk) version to install it.  Apart from that problem the tests aren't passing either so you have to `mvn clean install -Dmaven.test.skip=true` after you set your Javaversion to 8. Hope this helps – lets see if the installed version works cuz i had a bad experience with the node and python version of the sdk that simply does not work and now i am trying the java version and was running in the exact problem you have.

**Comment by Mafyak** [comment]
Same issue here when I use Java 11, but works with Java 8 with skipped tests.

**Comment by michel-bailleul** [comment]
To fix it, upgrade the Lombok dependency by using the latest version.

In the "pom.xml" file, replace :
`<version>1.16.18</version>`
by
`<version>1.18.24</version>`

Works with Java 8, 11 & 17
