### ISSUE TITLE
CRITICAL: Dependency not found

### ISSUE THREAD

**Issue by paalg** [Kucoin/kucoin-java-sdk#49]
When adding the dependency published in the readme file to my pom.xml file, I get the error message "Cannot resolve com.kucoin:kucoin-java-sdk:1.0.6". The project is actually not available in the Maven repositories:
https://repo.maven.apache.org/maven2/com/

After some research I found there is a fork off this project in the Maven repositories that actually exists (com.gruelbox.kucoin-java-sdk).

        <dependency>
            <groupId>com.gruelbox</groupId>
            <artifactId>kucoin-java-sdk</artifactId>
            <version>2.0.0</version>
        </dependency>

I hope you can update your readme file, or maybe make sure your project is available in the Maven repository.

**Comment by Samicheaterb** [comment]
THANK YOU

**Comment by abolfazlimahdi** [comment]
What has happened to this issue? I have the same problem here. should we use the other repo that was mentioned "com.gruelbox.kucoin-java-sdk"?

**Comment by rohit-gandhe** [comment]
This is very dangerous. Unless you check the forked code, you would have no idea what that code is doing. For all you know, it will send your key and secret to a malicious developer. If you have any money in your kucoin account, I'd just follow the directions in the readme. mvn clean install and then add dependency into your project.

BTW, this is very irresponsible of the kucoin dev team to not publish this into maven central and leave the developers using a forked and abandoned lib. A big thumbs down!!

**Comment by paalg** [comment]
You are right @rohit-gandhe, it is a huge security issue!
I am changing the title of the issue hoping to get the attention of the developement team.

**Comment by xiaoshengaimm** [comment]
<dependency>
        <groupId>com.gruelbox</groupId>
        <artifactId>kucoin-java-sdk</artifactId>
        <version>2.0.0</version>
    </dependency>

in github this fork was abandoned.....

**Comment by ManufactoryOfCode** [comment]
Download this project and use command
mvn clean install -DskipTests
With that you will install it into your local repository.
