### ISSUE TITLE
deposit multi address

### ISSUE THREAD

**Issue by pedram1995kzm** [Kucoin/kucoin-java-sdk#52]
hi
in this api i can only one address for each coin like BTC
so my users in website should have unique deposit address for BTC
otherwise how can I check who has deposit?
they all have same deposit address!

**Comment by ManufactoryOfCode** [comment]
I think that each useraccount has different address for each coin which is connected to MAIN account. However you can create subaccounts (there is a maximum number however) and those have their own sets of deposit addresses, but the main useraccount will be in charge of them. Never tried it, but maybe that's what you are looking for.

**Comment by iamalanal** [comment]
Is the issue solved?

**Comment by ISAAC-XXYYZZ** [comment]
Generally speaking, for a given coin under an account, a specific network corresponds to a single address. Our SDK is consistent with the product in this regard. 
I believe that if you have developed your own website and are using our address for deposits, the appropriate approach would be to manage your own user addresses, ledger information, and so on, to keep track of users' deposit records. Then, you can consolidate the funds and transfer them to the KuCoin account.
