### ISSUE TITLE
how to disable log in console

### ISSUE THREAD

**Issue by zhuozhongcao** [Kucoin/kucoin-java-sdk#67]
like this: 

16:59:53.261 [pool-2-thread-22] DEBUG c.k.s.r.i.AuthenticationInterceptor - originToSign=*/api/v1/accounts?currency=&type=trade
16:59:53.261 [pool-2-thread-22] DEBUG c.k.s.r.i.AuthenticationInterceptor - method=GET,endpoint=/api/v1/accounts
16:59:53.261 [pool-2-thread-22] DEBUG c.k.s.r.i.AuthenticationInterceptor - signature=*

**Comment by iamalanal** [comment]
Try adjusting the log level of your logback
